name: Build GlintColorizer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - run: chmod +x GlintColorizer/gradlew
      - run: cd GlintColorizer && ./gradlew setupDecompWorkspace
      - run: cd GlintColorizer && ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: GlintColorizer-1.0.0
          path: GlintColorizer/build/libs/GlintColorizer-1.0.0.jar
